#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

NAME=tvpxy
PROG=/usr/bin/$NAME


get_config() {
    config_get_bool enabled $1 enabled "0"
    config_get netdev $1 netdev ""
    config_get port $1 port 5555
}

start_service() {
    config_load $NAME
    config_foreach get_config $NAME
    [ $enabled != "1" ] && return 1

    echo "SERVICE $NAME START"

    ARGS="--net=$netdev --port=$port"

    procd_open_instance
    procd_set_param command $PROG $ARGS
    procd_set_param stderr 1
    procd_set_param file /etc/config/${NAME}
    procd_set_param pidfile /var/run/${NAME}.pid
    procd_set_param respawn
    procd_set_param user root
    procd_close_instance
}

stop_service() {
    echo "SERVICE $NAME STOP"
    rm -f /var/run/${NAME}.pid
    killall $NAME
}

reload_service() {
    echo "SERVICE $NAME RELOAD"
    stop
    start
}
